Update 3-merge-your-pull-request.yml
custom step for now

diff --git a/.github/workflows/3-merge-your-pull-request.yml b/.github/workflows/3-merge-your-pull-request.yml
--- a/.github/workflows/3-merge-your-pull-request.yml
+++ b/.github/workflows/3-merge-your-pull-request.yml
@@ -54,11 +54,63 @@ jobs:
         with:
           fetch-depth: 0 # Let's get all the branches.
 
-      # In README.md, switch step 2 for step [45X].
-      - name: Update to step [45X]
-        uses: skills/action-update-step@v2
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          from_step: 3
-          to_step: \\[45X\\]
-          branch_name: cd
+      # Custom step finish here: close 3; open 4, 5, and X; set step to X
+      - name: Update to show remaining steps
+        run: |
+          echo "Check that all required env variables are set"
+          if [ -z "$TO_STEP" ]
+          then
+            echo "TO_STEP is unset or set to the empty string"
+            exit 1
+          fi
+          if [ -z "$FROM_STEP" ]
+          then
+            echo "FROM_STEP is unset or set to the empty string"
+            exit 1
+          fi
+          if [ -z "$GITHUB_TOKEN" ]
+          then
+            echo "GITHUB_TOKEN is unset or set to the empty string"
+            exit 1
+          fi
+
+          echo "Check that we are on FROM_STEP"
+          if [ "$(cat .github/steps/-step.txt)" != $FROM_STEP ]
+          then
+            echo "Current step is not $FROM_STEP"
+            exit 0
+          fi
+
+          echo "Make sure we are on the base branch ($BASE_BRANCH_NAME)"
+          git checkout $BASE_BRANCH_NAME
+
+          echo "Update the step to TO_STEP"
+          NEXT_STEP=$(cat .github/steps/[$TO_STEP]-*.md)
+          HEADER=$(awk '/<header>/,/<\/header>/' README.md)
+          FOOTER=$(awk '/<footer>/,/<\/footer>/' README.md)
+          echo -e "$HEADER\n\n$NEXT_STEP\n\n$FOOTER" > README.md
+
+          echo "Update step file to TO_STEP"
+          echo "$TO_STEP" > .github/steps/-step.txt
+
+          echo "Commit the files, and push to base branch"
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          git add README.md
+          git add .github/steps/-step.txt
+          git commit --message="Update to $TO_STEP in STEP and README.md"
+          git push
+
+          echo "If BRANCH_NAME, update that branch as well"
+          if git show-ref --quiet refs/heads/$BRANCH_NAME
+            then
+              git checkout $BRANCH_NAME
+              git cherry-pick $BASE_BRANCH_NAME
+              git push
+            else
+              echo "Branch $BRANCH_NAME does not exist"
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          FROM_STEP: 3
+          TO_STEP: 45X
